export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function CVLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
    <>
    {children}
    <h1>Layout CV</h1>
    </>
    )
  }
  