export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'tomato',
            padding: '1rem'
          }}
        >
          HEADER
        </header>
        <main>
          {children}
        </main>
        <footer
          style={{
            backgroundColor: 'lightgreen',
            padding: '1rem'
          }}>
          FOOTER
        </footer>
      </body>
    </html>
  )
}
